### ISSUE TITLE
Memory overload

### ISSUE THREAD

**Issue by OmriBaso** [earthquake/Socks5Server#1]
If you inspect your code while running, It can be seen that the RAM is going up really high while browsing the internet using this proxy, I have tried to move the entire logic of the application to the HEAP and free memory when needed, but that was not sucessful.

I also fixed your authentication with username and password since It did not work out-of-the-box.

contact me if you wish to fix this lovely project of yours.
we need to fix the RAM problem, and then it is pretty solid.

**Comment by earthquake** [comment]
Thanks for taking a look, much appreciated. Feel free to send a pull request or many to fix these issues.
By your description, it seems that there is a memory leak in the code, which needs to be fixed indeed. Unfortunately I won't be able to take a deeper look in the next month, maybe a bit later, but I certainly will have some time to review a pull request is there is any.

**Comment by OmriBaso** [comment]
Hey,

I already fixed it!
Gonna send you a push in 30 minutes!

**Comment by earthquake** [comment]
merged your pull request, thanks for your works.
